# Generated by Django 2.2.4 on 2019-08-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('profecieny', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
