# Generated by Django 2.2.4 on 2019-08-20 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tech',
            table='teck_stack',
        ),
    ]
